from flet import colors

#COLORES PRINCIPALES
PRIMARY_COLOR = "#051923"
INDUSTRY_COLOR = "#7692FF"
NINDUSTRY_COLOR = "#FFE74C"
SECONDARY_COLOR = "#ABD2FA"
BACKGROUND_COLOR = colors.WHITE

SUCCESS_COLOR = "#5EF850"
ERROR_COLOR = "#EC2E15"
WARNING_COLOR = "#FFE74C"
